stages:
- deploy

deploy-to-gcp:
  stage: deploy
  before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  script:
  # cfr. https://docs.gitlab.com/ee/ci/ssh_keys/README.html
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - tar zcf ../NodeAPI.tar.gz ./Back-end/NodeAPI
  
  - scp -o StrictHostKeyChecking=no ../NodeAPI.tar.gz rober@35.214.82.56:/home/rober/
  
  - ssh rober@35.214.82.56 "sudo rm /var/www/NodeAPI.tar.gz && sudo mv /home/rober/NodeAPI.tar.gz /var/www/ && sudo rm -rf /var/www/NodeAPI && sudo tar zxf /var/www/NodeAPI.tar.gz -C /var/www/ && sudo cp -r /var/www/Back-end/NodeAPI /var/www && sudo rm -r /var/www/Back-end && cd /var/www/NodeAPI && sudo npm install && sudo forever stopall && sudo DB_PASSWORD=$(cat ../DB_PASSWORD.txt) forever start server.js"
  
  only:
    changes:
      - NodeAPI/